"""Internal implementations for the skills module."""

from .github import (
    GitHubFetchResult,
    ParsedGitHubURL,
    fetch_github_source,
    fetch_github_source_with_info,
    get_default_branch,
    get_latest_commit_sha,
    get_remote_tree_hash,
    get_remote_tree_symlinks,
    parse_github_url,
    rename_single_skill_dir,
    validate_skill_name_for_path,
)
from .manager import (
    GITHUB_SHORTHAND_RE,
    SkillInfo,
    StableLocalSource,
    acquire_local_source_snapshot,
    add_builtin,
    add_local,
    copy_skill_dir,
    copy_skill_snapshot,
    detect_skills,
    fail_on_symlinks,
    has_hidden_or_excluded_component,
    is_github_shorthand,
    parse_github_shorthand,
    remove_skill,
    resolve_source,
    snapshot_skill_dir,
)
from .origin import (
    capture_origin_state,
    compute_content_hash,
    compute_content_hash_with_reason,
    get_all_origins,
    get_origin,
    migrate_origin_v2,
    prune_orphan_origins,
    record_origin,
    restore_origin_state,
    update_origin,
)
from .origin import (
    remove_origin as remove_origin_record,
)
from .tracking import (
    get_missing_skill_ids,
    get_tracked_skill_ids,
    get_untracked_skill_ids,
    scan_installed_skill_ids,
)
from .validation import validate_skill_record
from .zip_handler import (
    ZipExtractResult,
    ZipSource,
    extract_opened_zip,
    extract_zip,
    is_zip_symlink_entry,
    open_zip_source,
    zip_has_symlink_entries,
    zip_hidden_or_excluded_symlink_entries,
)

__all__ = [
    "resolve_source",
    "detect_skills",
    "add_builtin",
    "add_local",
    "acquire_local_source_snapshot",
    "StableLocalSource",
    "copy_skill_dir",
    "copy_skill_snapshot",
    "snapshot_skill_dir",
    "fail_on_symlinks",
    "has_hidden_or_excluded_component",
    "remove_skill",
    "SkillInfo",
    "validate_skill_record",
    "parse_github_url",
    "fetch_github_source",
    "fetch_github_source_with_info",
    "get_default_branch",
    "get_latest_commit_sha",
    "get_remote_tree_hash",
    "get_remote_tree_symlinks",
    "rename_single_skill_dir",
    "validate_skill_name_for_path",
    "ParsedGitHubURL",
    "GitHubFetchResult",
    "GITHUB_SHORTHAND_RE",
    "is_github_shorthand",
    "parse_github_shorthand",
    "record_origin",
    "capture_origin_state",
    "restore_origin_state",
    "remove_origin_record",
    "get_origin",
    "get_all_origins",
    "compute_content_hash",
    "compute_content_hash_with_reason",
    "update_origin",
    "migrate_origin_v2",
    "prune_orphan_origins",
    "scan_installed_skill_ids",
    "get_tracked_skill_ids",
    "get_untracked_skill_ids",
    "get_missing_skill_ids",
    "ZipExtractResult",
    "ZipSource",
    "extract_opened_zip",
    "extract_zip",
    "is_zip_symlink_entry",
    "open_zip_source",
    "zip_has_symlink_entries",
    "zip_hidden_or_excluded_symlink_entries",
]
